version: '3.3'

services:

  iot-api:
    image: cinekdbw/iot-api
    restart: always
    ports:
      - 17631:80
  
  iot-vue:
    image: cinekdbw/iot-vue
    restart: always
    ports:
      - 17632:8080
  
  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    restart: always
    ports:
        - 17633:15672
    environment:
        - RABBITMQ_USERNAME=dotnetowiec
        - RABBITMQ_PASSWORD=kocham.Net!
        - RABBITMQ_VHOST=iot
